# Data files and paths
data:
  # Save / load, train : val : test : scaler files
  train_file: "direct_mttbar_train.h5"
  val_file: "direct_mttbar_val.h5"
  test_file: "direct_mttbar_test.h5"
  scaler_file: "direct_mttbar_scaler_info.h5"

  # Batching 
  batch_size: 4096
  num_workers: 4
  pin_memory: true

  # Use KL Divergence in loss loop
  use_kl_divergence : true

# Preprocessing options
preprocessing:

  # Use larger reco file size 
  use_large_reco: true

  # Use direct regression (false chooses top & antitop px,py,pz,E)
  use_direct_regression: true

  # Use mass loss (used for kinematic regression to improve px,py,pz,E)
  use_mass_loss: false

  # Use truth and predicted lepton vectors (used for spin observables regression)
  use_truth_lepton: false
  use_pred_lepton: false

  # Select direct targets
  direct_targets:
    - "mttbar"

# Current possible targets are "mttbar", "cos_theta_star", "cos_theta_ttbar", "cos_x_plus_minus", "cos_N_plus_minus

# Saving configuration
saving:
  loss_curve: "direct_parameters_loss_curve.png"
  evaluation_results: "direct_parameters_evaluation_results.h5"